### ISSUE TITLE
exception in connect()

### ISSUE THREAD

**Issue by tdtooke** [lanternbugs/lanternicc#6]
This is from the source.  I'm a big fan and I wanted to take a peak at the absolute latest.  That's the error I get when I try to sign on to ICC.  No problems at all with your main release, this is from your latest.

**Comment by lanternbugs** [comment]
sounds like a timestamp on icc or timeseal on fics issue.. the default code is set with the fics build of though so you want timestamp working. in chessbot4.java connect around line 680-690 there's this Class tsSocketClass = Class.forName("free.chessclub.timestamp.TimestampingSocket");
      Constructor tsSocketConstructor = tsSocketClass.getConstructor(new Class[]{String.class, int.class});

        requestSocket = (Socket)tsSocketConstructor.newInstance(new Object[]{sharedVariables.chessclubIP, new Integer(sharedVariables.chessclubPort)});

if you change those 3 lines to just a new socket("ip adress") like you see a catch do a bit further down it would work if timestamp is your issue. the free files ideally should come out of the Jar in particular for the timestamp timeseal setup.  they share timestamp/timeseal some of the same what i call a files stuff like a.java and you need the chessclub set in when its a chessclub build and the fics when its a fics build or it wont connect.

**Comment by lanternbugs** [comment]
> This is from the source. I'm a big fan and I wanted to take a peak at the absolute latest. That's the error I get when I try to sign on to ICC. No problems at all with your main release, this is from your latest.

I built from source today.  from the lantern jar ( you can get linux download copy on lantern chess.com or get jar out of mac package) you need free/chessclub/ folder and free/a/ folder this is timestamp. if you paste them in, the exception from connect goes away.  timetstamp is icc's move lag compensation that is on in non pool games so we get it from them and its not in source. changing the chessbot4 socket to a regular socket would then not need timestamp to work but you miss lag compensation. 
 Also i updated the free files with my source. looks like on my java version on this computer free/util/audio java files are erroring. so you may need to grab those class files from jar to have sound.

**Comment by tdtooke** [comment]
Thanks!  I'll give that a try when I get home today.

**Comment by sjb-2812** [comment]
Can that timestamp be used for other clients too? No one seems to be able to help on ICC when I ask

**Comment by lanternbugs** [comment]
contact icc at icc@chessclub.com or support@chessclub.com for questions about chessclub clients outside lantern. I don't know what their policy is or if they would allow a client to use another's timestamp but its technically possible.

**Comment by sjb-2812** [comment]
Thanks - I've tried those addresses, they tell me to ask on ICC - where nothing happens when I ask for help
